version: "3.7"
services:
  db:
    platform: linux/x86_64
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - projectdata:/var/lib/postgresql/data
    networks:
      - mired
  
  backend:
    depends_on:
      - db
    image: cyberlearnbackend:0.0.1
    restart: always
    ports:
      - '3000:3000'
    expose:
      - '3000'
    environment:
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_NAME: 'db'
    networks:
      - mired

volumes:
  projectdata:
  
networks:
  mired: