name: Docker Build & Push

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Obtener el último tag de Git
        run: echo "IMAGE_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker con el tag
        run: |
          docker build -t domi0620/cyberlearnbackend:${{ env.IMAGE_TAG }} .
          docker tag domi0620/cyberlearnbackend:${{ env.IMAGE_TAG }} domi0620/cyberlearnbackend:${{ env.IMAGE_TAG }}

      - name: Subir imágenes a Docker Hub
        run: |
          docker push domi0620/cyberlearnbackend:${{ env.IMAGE_TAG }}
